name: gurdaspur_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/images/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
